### PR TITLE
Added ability to delete prompt

### LINKED ISSUE #2: Ability to delete a prompt
We need to have the ability to delete a prompt.

add a service method to `prompts.service.ts` to delete the prompt. You'l use Prisma to delete it (look at the other methods in the service).

Then add a `deletePrompt` mutation to the `prompts.resolver.ts`.

The Delete button should be displayed as follows:
image

There's already a prompt deletion confirmation modal implemened (check out `apps/console/src/app/pages/prompts/[promptId]/index.tsx` line 69). So all in all it's a fun task.

p.s. you'll need to adjust the Prisma Schema to cascade delete all dependants of a Prompt when you delete it. You can see how to do that [here](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions).

### PR DESCRIPTION
**Pull request by AyanDas348**
Fixes #2 

In prisma.schema:
Added onDelete: Cascade directive to the relationships between Prompt and its dependents (PromptVersion, PromptEnvironment, PromptExecution).

In the code files:

Added deletePrompt method in prompts.service.ts to delete a prompt using Prisma.
Added deletePrompt mutation in prompts.resolver.ts to expose the delete functionality.

### CODE REVIEW

**Comment by arielweinberger** [comment]
Good progress @AyanDas348 that's awesome!

With regards to the Prisma schema, we need to make sure to include the migration file in the PR too.

You can run a migration as follows:
```
npx dotenv-cli -e apps/server/.env -- npx prisma migrate dev --schema apps/server/prisma/schema.prisma
```

Then you'll give it a name and it's all good.

**Comment by arielweinberger** [comment]
Also there seem to be changes introduced in `MetricContext` which is unrelated.

**Comment by AyanDas348** [comment]
Okay I'll make the updates.

**Comment by arielweinberger** [comment]
Can you please fix formatting? `npx nx format:write`

**Comment by arielweinberger** [comment]
Will test shortly.

**Comment by AyanDas348** [comment]
Hi @arielweinberger did you get a chance to check

**Comment by arielweinberger** [comment]
Hi @AyanDas348 we'll do that soon. Don't worry.

**Comment by AyanDas348** [comment]
@arielweinberger thanks! Meanwhile is there anything else I can work on? Maybe other projects that you currently are working on. Let me know if there's anything.

**Comment by AyanDas348** [comment]
The discord link for pezzo is showing up as invalid. How can I join discord? @arielweinberger

**Pull request closed without merging**
