### PR TITLE
chore(deps): update nx to v16

### PR DESCRIPTION
**Pull request by overbit**
This PR update the nx dependencies to the current latest, simplify the configuration and fixes some nx cache configurations

### CODE REVIEW

**Comment by overbit** [comment]
Blocked by #61

**Comment by arielweinberger** [comment]
I'll wrap #61 later today @overbit

**Comment by arielweinberger** [comment]
Should be fixed by #72 - apologies for the conflicts.

**Comment by arielweinberger** [comment]
I'm going to close this one  for now, due to inactivity.

**Pull request closed without merging**
