### PR TITLE
chore: update nx to v16.2.1 (#41)

### PR DESCRIPTION
**Pull request by arielweinberger**
* chore: update nx to latest version

* fix: generated files to be ignored to avoid never-ending restart of local dev server

* fix(server): generation targets nx cache configuration

* fix(common): generation targets nx cache configuration

* chore(server): simplify webpack configuration to use nx plugin defaults

### CODE REVIEW

**Comment by arielweinberger** [comment]
FYI @overbit I've identified a bug with Nx 16, reported it [here](https://github.com/nrwl/nx/issues/17146). In the meantime I am working on a workaround and will merge.

**Comment by overbit** [comment]
Sad that I didn't get the contributor flag. @arielweinberger you should not squash community PRs otherwise you will lose contributors

**Comment by arielweinberger** [comment]
@overbit  dang! still new to this open source project thingy. Sorry!

What about making a change to the README.md to explain a bit about the Pezzo tech stack (Nx Workspaces, Node.js, NestJS, GraphQL, React) etc? Promise not to squash it!

**Comment by arielweinberger** [comment]
By the way, I am quite certain you were registered as a contributor:
https://github.com/pezzolabs/pezzo/graphs/contributors

**Comment by overbit** [comment]
oh nice! then GitHub updated its logic for contributors taking into account the co-authored too!

I'm really surprised about the docker build failure BTW, since locally was working fine 🤷🏻

**Pull request merged**
