### PR TITLE
Use OpenAPI json

### LINKED ISSUE #191: Add always-up-to-date REST API to the docs
### Proposal

Depends on #190.

- Once we have an auto-generated OpenAPI spec (#190), we can insert it into our documentation site.
- Our docsite can be found in `/docs`.
- We use [Mintlify](https://mintlify.com/docs/quickstart). Mintlify has a feature for this. [Read more about it here](https://mintlify.com/docs/api-playground/openapi).

### Use-Case

_No response_

### Is this a feature you are interested in implementing yourself?

No

### PR DESCRIPTION
**Pull request by SniperBuddy101**
- What is this pull request for?
Add always-up-to-date REST API to the docs 

Resolves #191 

### Screenshot
image

Process:

1. Download the OpenAPI json file through this URL - https://api.staging.pezzo.ai/api/spec-json (Subject to change)
2. Save the JSON file with the name `open-api.json` in the docs directory (Mintlify).
3. Generate MDX files for the endpoints using the following command in the docs directory:
`npx @mintlify/scraping@latest openapi-file open-api.json -o api-reference`
4. Copy the generated output in the navigation section of `mint.json` file.
5. The MDX files contain just the open api endpoints.
6. The navigation section can be customised.

Have already auto generated the MDX files for the current API spec.

### CODE REVIEW

**Comment by arielweinberger** [comment]
Thanks @SniperBuddy101 looks excellent overall. Could you please:

- Put the API docs under an "API Reference" tab so that it's separate from the rest of the docs
- Make sure all operations are in the same menu

**Comment by SniperBuddy101** [comment]
@arielweinberger 
Will make those changes.

Yes, I also think that it'll be better if we auto generate them at build time.
I'd like to take that as well.

**Comment by arielweinberger** [comment]
@SniperBuddy101 yup just updated my comment!

**Comment by SniperBuddy101** [comment]
### Updated tabs:

image
image

**Comment by arielweinberger** [comment]
Amazing work!

**Review by arielweinberger — APPROVED** [review]

**Pull request merged**
