### PR TITLE
feat: allows merging pezzo options with openai options

### PR DESCRIPTION
**Pull request by lh0x00**
Being able to only use one of the two is a limitation, and I encountered the fact that if I used pezzo's `variables` I couldn't add `headers` to the request, so I suggested updating it.

Please take a look and merge if it's ok.

### CODE REVIEW

**Comment by lh0x00** [comment]
@arielweinberger thanks for review

**Comment by arielweinberger** [comment]
I understand the need - thanks for the PR @lh0x00. I was thinking to move the OpenAI options to the 3rd argument rather than the 2nd, so no merging, just because some of the parameter names used in Pezzo such as `properties`, `variables` and `cache` could potentially create conflicts with future parameters introduced by OpenAI. Thoughts?

**Comment by lh0x00** [comment]
@arielweinberger I agree with this, and I will update it.

**Comment by lh0x00** [comment]
hi @arielweinberger do you need me to update anything else? because I'm waiting for its release to use directly instead of a fork of pezzo. If possible, please help me review it as soon as possible, thank you.

**Comment by arielweinberger** [comment]
@lh0x00 Will merge ASAP. Can you fix formatting? `npx nx format:write --all`

**Comment by lh0x00** [comment]
@arielweinberger I have updated it again, thanks for review.

**Comment by arielweinberger** [comment]
Please make the 3rd argument optional. CI fails.

**Comment by lh0x00** [comment]
I updated it.

**Comment by arielweinberger** [comment]
This should be alright @lh0x00 I'll run some tests and if all is good I'll push and release.

**Comment by arielweinberger** [comment]
@lh0x00 should be live at `@pezzo/client@0.4.18`

**Comment by lh0x00** [comment]
thank you so much, @arielweinberger

**Pull request merged**
