### PR TITLE
feat(console): added drag and drop feature to chat message

### PR DESCRIPTION
**Pull request by adityapuri75**
i have attached a screen recording

https://github.com/pezzolabs/pezzo/assets/49858681/3ef80f6d-68dd-4cb6-bd70-37ea828cee63

### CODE REVIEW

**Comment by adityapuri75** [comment]
Hii @arielweinberger, is there any update on this PR?

**Comment by arielweinberger** [comment]
Hi Aditya, I'll get to review it in the weekend.

**Comment by arielweinberger** [comment]
@adityapuri75 Functionality wise it is almost fine, I have two comments:

1) Unless you move a message precisely onto another, it's very hard to get the reorder right.
2) There is no visual indicator that "if I let go of my mouse button now, something will happen". Some sort of border of the message, something that indicates that I am currently holding my mouse over a functional position would be good.

**Review by arielweinberger — CHANGES_REQUESTED** [review]
@adityapuri75 Functionality wise it is almost fine, I have two comments:

1. Unless you move a message precisely onto another, it's very hard to get the reorder right.
2. There is no visual indicator that "if I let go of my mouse button now, something will happen". Some sort of border of the message, something that indicates that I am currently holding my mouse over a functional position would be good.

**Comment by adityapuri75** [comment]
Thanks for reviewing @arielweinberger, i will work on these points over the weekend.

**Comment by arielweinberger** [comment]
Closing this PR for now. Feel free to reopen once the solution is working. Note that we switched to `shadcn/ui` and `react-hook-form` in v0.7.0.

**Comment by adityapuri75** [comment]
I have been sick from past few weeks, will surely complete it and reopen the PR soon :)

**Pull request closed without merging**
